### ISSUE TITLE
Adding Data-Generation functionallity

### ISSUE THREAD

**Issue by Art1k** [SmartBear/ready-api-testserver-client#11]
Hi guys,

I've been using SoapUI Pro and TestServer and for now i can't find Data generation functionality inside client. DataSource doesn't include data-generator like SoapUI and I need it in order to generate unique data inside test-steps without providing\generating it separately.
I'm using 1.0.2 version

<groupId>com.smartbear.readyapi</groupId>
<artifactId>ready-api-testserver-client</artifactId>
<version>1.0.2</version>

**Comment by spindelmanne** [comment]
Thanks for your comment! It's great to learn what customers need; this helps us setting the priorities.

There still a gap in functionality between test recipes and "classic", XML-based Ready! API projects. Over time this gap will be bridged, so bear with us!

**Comment by Art1k** [comment]
Thanks,
This functionality is very valuable, since you have to gather or implement all the data generators by yourself in java,by adding this to recipes,you save a lot of headache. 
Do you have ETA for this one,  yesterday as we spoke, seemed like it exists in next version

**Comment by prakashmrec** [comment]
All data generators are supported in TestServer and TestServer client has been updated to be able to add them to recipes.
