### ISSUE TITLE
Debugging requests

### ISSUE THREAD

**Issue by Art1k** [SmartBear/ready-api-testserver-client#14]
I've found no debugging description or reference,it would be great if you could provide any documentation or workarounds for debugging requests,since there's no obvious way to that,could you please assist

**Comment by olensmar** [comment]
Hi!

By "debugging" do you mean getting access to the http transaction log for the executed Test (which we are working on but don't support yet)? Or are you looking for something else?

/Ole

**Comment by Art1k** [comment]
Yes,since for now i have to somehow get info on why my tests are failing.

Workaround:

.addStep(groovyScriptStep("def response = testRunner.testCase.getTestStepByName(\"Create Lead\").httpRequest.getResponseContentAsString()\n"+
                                      "def request = testRunner.testCase.getTestStepByName(\"Create Lead\").httpRequest.getRequestContent()\n" +
                                      "return \"\\n Request: \" + request + \" \\n Response: \" + response"
            ))

**Comment by olensmar** [comment]
hehe - that's very creative of you - thanks for sharing :-)

**Comment by prakashmrec** [comment]
This feature has been implemented in TestServer now and client has convinience methods on TestStepResult to get the response for particular exeuction of a test step.
