### ISSUE TITLE
[Property transfer] Unable to set transferName

### ISSUE THREAD

**Issue by Art1k** [SmartBear/ready-api-testserver-client#15]
Couldn't find suitable description on implementing property transfer.
getting:

Error received when sending test recipe to server
null
	at com.smartbear.readyapi.client.execution.ApiClientWrapper.invokeAPI(ApiClientWrapper.java:141)
	at com.smartbear.readyapi.client.execution.CodegenBasedSmartestApiWrapper.invokeAPI(CodegenBasedSmartestApiWrapper.java:194)
	at com.smartbear.readyapi.client.execution.CodegenBasedSmartestApiWrapper.postTestRecipe(CodegenBasedSmartestApiWrapper.java:63)
	at com.smartbear.readyapi.client.execution.RecipeExecutor.doExecuteTestCase(RecipeExecutor.java:94)
	at com.smartbear.readyapi.client.execution.RecipeExecutor.executeRecipe(RecipeExecutor.java:70)
	at com.tradefxl.eventhub.autotests.model.BaseTest.execTestRecipe(BaseTest.java:35)
	at com.tradefxl.eventhub.autotests.LeadPlusMT4Test.createLead(LeadPlusMT4Test.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

My guess that he can't find step or property

**Comment by olensmar** [comment]
could you print out the TestRecipe and share? 

```
System.out.println( recipe.toString() );
```

should do the trick... 

/Ole

**Comment by Art1k** [comment]
{
	"searchProperties": false,
	"maintainSession": false,
	"abortOnError": false,
	"failTestCaseOnError": true,
	"discardOkResults": false,
	"socketTimeout": null,
	"testCaseTimeout": null,
	"testSteps": [{
		"type": "REST Request",
		"name": "Create Lead",
		"headers": {
			"Cookie": ["JSESSIONID=D1AAB9B7FFE72A9BE1E4E3E5A3464B19; Path=/; HttpOnly"]
		},
		"method": "POST",
		"entitizeParameters": false,
		"mediaType": "application/json",
		"encoding": null,
		"timeout": null,
		"requestBody": "RequestBody",
		"followRedirects": false,
		"postQueryString": false,
		"assertions": [{
			"type": "Valid HTTP Status Codes",
			"validStatusCodes": [200]
		}, {
			"type": "JsonPath Count",
			"jsonPath": "$.result",
			"allowWildcards": false,
			"expectedCount": 1
		}, {
			"type": "JsonPath Match",
			"jsonPath": "$.result.machineId",
			"allowWildcards": false,
			"expectedContent": "79b16639-b893-422e-bd04-a5161728dac9"
		}],
		"parameters": [{
			"type": "TEMPLATE",
			"name": "method",
			"value": "WebSiteService.createAdvancedLead"
		}],
		"authentication": null,
		"URI": "http://ApiURL/JSON-RPC"
	}, {
		"type": "Groovy",
		"name": null,
		"script": "def response = testRunner.testCase.getTestStepByName(\"Create Lead\").httpRequest.getResponseContentAsString()\ndef request = testRunner.testCase.getTestStepByName(\"Create Lead\").httpRequest.getRequestContent()\nreturn \"\\n Request: \" + request + \" \\n Response: \" + response"
	}, {
		"type": "Property Transfer",
		"name": null,
		"transfers": [{
			"transferName": null,
			"source": {
				"sourceName": "Create Lead",
				"property": "Response",
				"pathLanguage": "JSONPath",
				"path": "$.result.id"
			},
			"target": {
				"targetName": "Lead Plus",
				"property": "customerID",
				"pathLanguage": null,
				"path": null
			},
			"failTransferOnError": false,
			"setNullOnMissingSource": false,
			"transferTextContent": false,
			"ignoreEmptyValue": false,
			"transferToAll": false,
			"transferChildNodes": false,
			"entitizeTransferredValues": false
		}]
	}, {
		"type": "REST Request",
		"name": "LeadPlus",
		"headers": {
			"Cookie": ["JSESSIONID=D1AAB9B7FFE72A9BE1E4E3E5A3464B19; Path=/; HttpOnly"]
		},
		"method": "POST",
		"entitizeParameters": false,
		"mediaType": "application/json",
		"encoding": null,
		"timeout": null,
		"requestBody": "",
		"followRedirects": false,
		"postQueryString": false,
		"assertions": [{
			"type": "Valid HTTP Status Codes",
			"validStatusCodes": [200]
		}, {
			"type": "JsonPath Count",
			"jsonPath": "$.result",
			"allowWildcards": false,
			"expectedCount": 1
		}],
		"parameters": [],
		"authentication": null,
		"URI": "http://ApiURL/JSON-RPC"
	}]
}

**Comment by Art1k** [comment]
It's impossible to proceed with test development without at least the ability to transfer properties between steps inside the same recipe. 

There is workaround instead of using property transfer:

.addStep(groovyScriptStep("\n" +
                    "import com.eviware.soapui.support.XmlHolder\n" +
                    "import groovy.json.JsonSlurper \n" +
                    "def responseJson = context.expand( '${Create Lead#Response}' ).toString()\n" +
                    "def slurper = new JsonSlurper()\n" +
                    "def json = slurper.parseText response\n" +
                    "def customerId = json.result.id\n" +
                    "log.info(customerId)\n" +
                    "testRunner.testCase.setPropertyValue( \"customerID\", customerId )\n" +
                    "return customerId"
))

**Comment by spindelmanne** [comment]
Property transfers are included in the recipe format. Doesn't that work for you? If so, why not?

**Comment by Art1k** [comment]
> Doesn't that work for you? If so, why not?

I specified the reason in the first post, why it doesn't work for me. Could you please assist with resolving this issue?

P.S: For the above groovy example,it works inside SoapUI and doesn't with TestServer:

`messages: [java.lang.NoClassDefFoundError: Could not initialize class groovy.json.internal.JsonParserCharArray, error at line: 6]`

**Comment by Art1k** [comment]
When i use this:

```
.addStep(propertyTransfer().named("UserData")
                            .addTransfer(PropertyTransferBuilder.newTransfer()
                                    .withSource(PropertyTransferSourceBuilder.aSource()
                                            .withSourceStep("CreateLead")
                                            .withProperty("Response")
                                            .withPathLanguage(PathLanguage.JSONPath)
                                            .withPath("$.result.id")
                                    )
                                    .withTarget(PropertyTransferTargetBuilder.aTarget()
                                            .withTargetStep("LeadPlus")
                                            .withProperty("customerID")
                                            .withPathLanguage(PathLanguage.JSONPath)
                                    )
                            )
                    )

```
I get this recipe:

```
{
		"type": "Property Transfer",
		"name": "UserData",
		"transfers": [{
			"transferName": null,
			"source": {
				"sourceName": "CreateLead",
				"property": "Response",
				"pathLanguage": "JSONPath",
				"path": "$.result.id"
			},
			"target": {
				"targetName": "LeadPlus",
				"property": "customerID",
				"pathLanguage": "JSONPath",
				"path": null
			},
			"failTransferOnError": false,
			"setNullOnMissingSource": false,
			"transferTextContent": false,
			"ignoreEmptyValue": false,
			"transferToAll": false,
			"transferChildNodes": false,
			"entitizeTransferredValues": false
		}]
	},
```

After brief investgation i didn't found any method that allowes to set :   

> "transferName": null,

So i guess due that i keep getting:
```
Error received when sending test recipe to server
null
```

**Comment by olensmar** [comment]
Hi,

I'm sorry for the delay on this - I've create a "property-transfer-name" branch that sets a default name internally - or allows you to specify the name in the newTransfer call - or by using named(...) - Can you build that locally and give it a try?

/Ole

**Comment by olensmar** [comment]
the branch also contains a corresponding fix for the Script TestStep - which also had a null name in your recipe above

**Comment by olensmar** [comment]
I've published a 1.0.3-SNAPSHOT build with these fixes to the sonatype snapshot repo - https://oss.sonatype.org/content/repositories/snapshots/com/smartbear/readyapi/ready-api-testserver-client/

**Comment by Art1k** [comment]
Thanks it seems to work now,but i have another question regarding the transfer.
I'm getting and error that "Missing target property", do i have an option to create this one during the transfer? Or how i can create an empty property to set the value later on without creating list with some random values to be overridden later.

**Comment by olensmar** [comment]
hm... do you get this when building the recipe? can you show how/when this happens?

**Comment by Art1k** [comment]
Sure,

First of all this syntax doesn't get me the value: .add("id", "${Step1#Password}")

I solved missing property by adding this to Step2:
```
.addMatrixParameter("customerID","")
.addMatrixParameter("Password","")
```

But essential Transfer look like the following:

```
.addStep(propertyTransfer().named("UserData")
                            .addTransfer(PropertyTransferBuilder.newTransfer()
                                    .withSource(PropertyTransferSourceBuilder.aSource()
                                            .withSourceStep("Step1")
                                            .withProperty("Response")
                                            .withPathLanguage(PathLanguage.JSONPath)
                                            .withPath("$.result.id")
                                    )
                                    .withTarget(PropertyTransferTargetBuilder.aTarget()
                                            .withTargetStep("Step2")
                                            .withProperty("customerID")
                                            .withPathLanguage(PathLanguage.JSONPath)
                                    )
                            ).named("CustomerID")
                            .addTransfer(PropertyTransferBuilder.newTransfer()
                                    .withSource(PropertyTransferSourceBuilder.aSource()
                                            .withSourceStep("Step1")
                                            .withProperty("Response")
                                            .withPathLanguage(PathLanguage.JSONPath)
                                            .withPath("$.result.password")
                                    )
                                    .withTarget(PropertyTransferTargetBuilder.aTarget()
                                            .withTargetStep("Step2")
                                            .withProperty("Password")
                                            .withPathLanguage(PathLanguage.JSONPath)
                                            .withPath("")
                                    )
                            ).named("Password")
                    )
```

> messages: [Error performing transfer [Transfer 0.28336682221610554] - Missing target property, Performed transfer [Transfer 0.021447445238803486]]

**Comment by olensmar** [comment]
ok - it makes sense that you need to add the properties to Step 2 to be able to target them - but you shouldn't be required to add 

```
.withPathLanguage(PathLanguage.JSONPath)
```

for either of your two targets.

Regarding the 

```
.add("id", "${Step1#Password}")
```

statement that should have worked - where/how were you adding that to the recipe?

**Comment by Art1k** [comment]
I'm using json builder. So I add an array element with .add(key,value)

**Comment by olensmar** [comment]
hmm... can you show (or send) the generated recipe?

**Comment by Art1k** [comment]
Sure,but I prefer to email you the sample,give me the address,where I can
send it

**Comment by olensmar** [comment]
sure - send it to ole dot lensmar at smartbear dot com - thanks!

**Comment by Art1k** [comment]
Did you receive it?

**Comment by olensmar** [comment]
yes thank you - i'll answer you shortly!

**Comment by prakashmrec** [comment]
This has been fixed in the TestServer, so it's not mandatory anymore to set a transer name. TestServer will create the transfer name if missing.
