### ISSUE TITLE
Step execution results getter

### ISSUE THREAD

**Issue by Art1k** [SmartBear/ready-api-testserver-client#18]
Since TestRecipe consists of testSteps that are corresponding to testCases it would be great to have an option to retrieve TestStep(TestCase) result in order to use it later for verification or other systems update.

**Comment by spindelmanne** [comment]
Yes! We're discussing how to do this best at the moment.

**Comment by olensmar** [comment]
@spindelmanne - @Art1k and I discussed this yesterday; the current result format is somewhat "convoluted" - we discussed creating some convenience methods to get results for individual teststeps which could lead the way for a simpler/richer format in the future.

**Comment by olensmar** [comment]
see https://github.com/SmartBear/ready-api-testserver-client/pull/19

**Comment by prakashmrec** [comment]
This has been implemented, closing the issue.
